텐서

In [1]:
import numpy as np
import tensorflow as tf

0D Tensor

In [3]:
t0 = tf.constant(1)
print(t0)

tf.Tensor(1, shape=(), dtype=int32)


1D Tensor(Vector)

In [5]:
t1 = tf.constant([1,2,3]) #하나의 축으로 연달아 있음
print(t1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


2D Tensor(Matrix)

In [7]:
t2 = tf.constant([[1,2,3],[4,5,6]]) # shape 2행 3열을 나타냄
print(t2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


3D Tensor (시계열 데이터)
features,timsteps,samples

In [8]:
t3= tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t3)


tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)


4D Tensor (4개의 축) 
# 주로 샘플, 높이,너비,컬러 채널을 가진 구조로 사용

In [9]:
t4 = tf.constant([[[[1,2],[3,4],[1,2],[3,4],[1,2],[3,4],[1,2],[3,4]]]])
print(t4)

tf.Tensor(
[[[[1 2]
   [3 4]
   [1 2]
   [3 4]
   [1 2]
   [3 4]
   [1 2]
   [3 4]]]], shape=(1, 1, 8, 2), dtype=int32)
