텐서

In [1]:
import numpy as np
import tensorflow as tf

0D Tensor

In [3]:
t0 = tf.constant(1)
print(t0)

tf.Tensor(1, shape=(), dtype=int32)


1D Tensor(Vector)

In [5]:
t1 = tf.constant([1,2,3]) #하나의 축으로 연달아 있음
print(t1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


2D Tensor(Matrix)

In [7]:
t2 = tf.constant([[1,2,3],[4,5,6]]) # shape 2행 3열을 나타냄
print(t2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


3D Tensor (시계열 데이터)
features,timsteps,samples

In [8]:
t3= tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(t3)


tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(3, 3, 3), dtype=int32)


4D Tensor (4개의 축) 
# 주로 샘플, 높이,너비,컬러 채널을 가진 구조로 사용

In [9]:
t4 = tf.constant([[[[1,2],[3,4],[1,2],[3,4],[1,2],[3,4],[1,2],[3,4]]]])
print(t4)

tf.Tensor(
[[[[1 2]
   [3 4]
   [1 2]
   [3 4]
   [1 2]
   [3 4]
   [1 2]
   [3 4]]]], shape=(1, 1, 8, 2), dtype=int32)


#텐서 데이터 타입
정수형 텐서:int32

실수형 텐서:float32

문자열 텐서:string

연산시 텐서의 타입 일치 필요

타입변환에는 tf.cast()


In [10]:
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [11]:
f = tf.constant(2.)
print(f)

tf.Tensor(2.0, shape=(), dtype=float32)


In [12]:
s = tf.constant('hi')
print(s)

tf.Tensor(b'hi', shape=(), dtype=string)


In [13]:
f16 = tf.constant(2., dtype=tf.float16)  # -> 32비트 float 타입을 16비트로 변환하고 dtype을 tf.float16 16비트로 변환시킴
print(f16)

tf.Tensor(2.0, shape=(), dtype=float16)


In [15]:
i8 = tf.constant(2, dtype=tf.int8)
print(i8)

tf.Tensor(2, shape=(), dtype=int8)


In [16]:
f32 = tf.cast(f16, tf.float32) #16비트였던 f16을 32로 cast(변화)함
print(f32)

tf.Tensor(2.0, shape=(), dtype=float32)


#텐서 연산

In [23]:
a = tf.constant(2)
b = tf.constant(5)

print(tf.add(a,b)) #더하기 연산자
print(tf.subtract(a,b)) #빼기 연산자

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(-3, shape=(), dtype=int32)


In [24]:
a = tf.constant(2)
b = tf.constant(5)

print(tf.add(a,b)) #더하기 연산자
print(tf.subtract(a,b)) #빼기 연산자
print(tf.multiply(a,b)) #곱하기 연산자
print(tf.divide(a,b)) #나눗셈 연산자

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(-3, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(0.4, shape=(), dtype=float64)


In [29]:
print(tf.cast(tf.constant(2),tf.float32)+ tf.constant(2.2)) #tensor에서는 int형+float형을 cast 직접 해줘야 함

tf.Tensor(4.2, shape=(), dtype=float32)


# 딥러닝 구조 및 학습

모델을 구성하는 레이어

입력 데이터와 그에 대한 목적

학습시에 사용할 피드백을 정의하는 손실함수

학습 진행 방식을 결정하는 옵티마이저

#레이어
1.신경망의 핵심 데이터 구조

2.하나 이상의 텐서를 입력받아 하나 이상의 텐서를 출력하는 데이터 처리 모듈

3.상태가 없는 레이어도 있지만, 대부분 가중치(Weight)라는 레이어 상태를 가진다.

4.가중치는 확률적 경사 하강법에 의해 학습되는 하나 이상의 텐서

    keras에서 사용하는 주요 레이어
    1.Dense
    2.Activation
    3.Flatten
    4.Input

In [40]:
from tensorflow.keras.layers import Dense

In [41]:
from tensorflow.keras.layers import Activation,Flatten,Input

#Dense
완전 연결 계층 (모든 노드가 서로 연결 된 상태)

노드수(유닛수), 활성화 함수(activation)등 지정

name을 통한 레이어간 구분 가능

★가중치 초기화(kernel_intializer)

In [43]:
Dense(10, activation='softmax') #softmax는 activation종류중 하나지만 가장 끝 값을 가져오는걸 의미

In [45]:
Dense(10, activation='relu', name = 'relu')

In [46]:
Dense(10, kernel_initializer = 'he_normal', name = 'Dense Layer')

Keras에서 제공하는 활성화 함수(Activation function) 종류는 : https://keras.io/ko/activations/

Dense layer에서 미리 activation 지정 할 수도 있지만 필요에 따라 별도로 레이어를 만들 수도 있다.


In [47]:
dense = Dense(10, activation='relu',name='Dense Layer')
Activation(dense)

#Flatten

배치 크기(or 데이터 크기)를 제외하고 데이터를 1차원으로 펼치는 작업

Ex) (128, 3, 2, 2) -> (128,12)

In [52]:
Flatten(input_shape=(128,3,2,2))

#Input
1.모델의 입력을 정의

2.shape, dtype을 포함

3.하나의 모델은 여러 개의 입력을 가질 수 있음

4.summary() 메소드를 통해서는 보이지 않음

In [53]:
Input(shape=(28,28), dtype=tf.float32)

<KerasTensor: shape=(None, 28, 28) dtype=float32 (created by layer 'input_1')>

In [54]:
Input(shape=(8,), dtype=tf.int32)

<KerasTensor: shape=(None, 8) dtype=int32 (created by layer 'input_2')>